import { chineseForSource, englishForSource } from '../i18n/translateSource'
import { ref } from 'vue'

export type UiLanguage = 'en' | 'zh-CN'

const UI_LANGUAGE_STORAGE_KEY = 'codex-web-local.ui-language.v1'

const zhCN: Record<string, string> = {
  'Display timezone': '显示时区',
  'Copy': '复制',
  'Copy code': '复制代码',
  'Copy failed': '复制失败',
  'Search timezones': '搜索时区',
  'Follow system': '跟随系统',
  'Applies to all pages in this browser.': '应用于本浏览器的所有页面。',
  'None': '无',
  'Minimal': '最低',
  'Low': '低',
  'Medium': '中',
  'High': '高',
  'Extra high': '极高',
  'No speech detected. Click again after speaking.': '未检测到语音，请说话后再次点击。',
  'No speech detected. Hold the mic and speak.': '未检测到语音，请按住麦克风说话。',
  'Microphone access was denied.': '麦克风访问被拒绝。',
  'Dictation failed.': '听写失败。',
  'Composio CLI shares the login and connections from this machine.': 'Composio CLI 使用本机的登录和连接状态。',
  'Authenticated': '已认证',
  'Connector': '连接器',
  'Auth': '认证',
  'Bearer token (optional)': 'Bearer Token（可选）',
  'Custom endpoint': '自定义端点',
  'Dismiss': '关闭',
  'Download': '下载',
  'Explore Plugins & Apps': '浏览插件与应用',
  'Exporting': '导出中',
  'Failed to share project. Use Download instead.': '分享项目失败，请使用下载。',
  'Hook Codex up to Gmail, Calendar, GitHub, Slack, Browser Use, and more so it can actually help with real work right away.': '将 Codex 连接到 Gmail、Calendar、GitHub、Slack、Browser Use 等工具，协助处理实际任务。',
  'Import Project': '导入项目',
  'Importing…': '导入中…',
  'Issue detected': '发现问题',
  'New in Codex': 'Codex 新功能',
  'Plugins are here': '插件已上线',
  'Plugins, apps, MCPs': '插件、应用、MCP',
  'Preparing project ZIP...': '正在准备项目 ZIP…',
  'Preparing...': '准备中…',
  'Scheduled work': '定时任务',
  'Share': '分享',
  'This browser blocked sharing the ZIP. Use Download instead.': '浏览器阻止了 ZIP 分享，请使用下载。',
  'sk-or-v1-... (optional, uses free keys if empty)': 'sk-or-v1-…（可选，留空使用免费 Key）',
  'Add new prompt': '添加提示词',
  'Disable plan mode': '关闭计划模式',
  'Enable plan mode': '启用计划模式',
  'Exit full screen composer': '收起输入框',
  'Expand composer': '展开输入框',
  'Prompt content': '提示词内容',
  'Prompt name': '提示词名称',
  'Remove prompt': '移除提示词',
  'RRULE: {rrule} · runs daily at {time}': 'RRULE: {rrule} · 每天 {time} 运行',
  'RRULE: {rrule} · runs every {count} minutes': 'RRULE: {rrule} · 每 {count} 分钟运行',
  'RRULE: {rrule} · runs every {count} hours': 'RRULE: {rrule} · 每 {count} 小时运行',
  'RRULE: {rrule} · runs every {count} days': 'RRULE: {rrule} · 每 {count} 天运行',
  '{name} plugin installed': '已安装插件 {name}',
  '{name} plugin uninstalled': '已卸载插件 {name}',
  '{name} plugin enabled': '已启用插件 {name}',
  '{name} plugin disabled': '已禁用插件 {name}',
  '{name} app enabled': '已启用应用 {name}',
  '{name} app disabled': '已禁用应用 {name}',
  'Opened {name} authorization': '已打开 {name} 授权页面',
  'No login URL returned for {name}': '未返回 {name} 的登录地址',
  'Failed to start login for {name}': '启动 {name} 登录失败',
  'Failed to connect {name}': '连接 {name} 失败',
  'Composio CLI login started': '已启动 Composio CLI 登录',
  'Composio CLI installed': '已安装 Composio CLI',
  'MCP servers reloaded': '已重新加载 MCP 服务器',
  'Export Project': '导出项目',
  'Rename project': '重命名项目',
  'Copy path': '复制路径',
  'Create chat fork': "创建会话分支",
  'Existing chat': "已有会话",
  'Add another automation': '添加另一个自动化',
  'Interval': '间隔',
  'Popular': '热门',
  'Date': '日期',
  'Plugin APIs unavailable in this Codex CLI. Update Codex CLI to use plugin catalog features.': '当前 Codex CLI 不支持插件 API，请更新 CLI 以使用插件目录。',
  'Apps APIs unavailable in this Codex CLI. Update Codex CLI to manage apps.': '当前 Codex CLI 不支持应用 API，请更新 CLI 以管理应用。',
  'MCP status APIs unavailable in this Codex CLI. Update Codex CLI to inspect MCP servers.': '当前 Codex CLI 不支持 MCP 状态 API，请更新 CLI 以查看 MCP 服务器。',
  'Composio is installed locally. Login to browse the live catalog, connect your accounts, and try simple actions from this machine.': '本机已安装 Composio。登录后可浏览实时目录、连接账号并试用操作。',
  'Open dashboard': '打开控制台',
  'Details': '详情',
  'No linked accounts yet.': '尚未关联账号。',
  'New automation': '新建自动化',
  'No saved accounts yet. Run `codex login`, then click reload.': '尚未保存账号。请运行 `codex login`，然后点击重新加载。',
  'Thread menu': "会话菜单",
  'Project menu': '项目菜单',
  'Archive chat and remove automations?': "归档会话并移除自动化？",
  'Delete thread?': "删除会话？",
  'Archive {title} and remove its heartbeat automations.': '归档“{title}”并移除其心跳自动化。',
  'Archive {title}. You can find it later in archived threads.': "归档“{title}”。之后可在已归档会话中找到它。",
  'Project automation': '项目自动化',
  'Edit automation': '编辑自动化',
  'Add automation': '添加自动化',
  '{count} total': '共 {count} 项',
  '{count} active': '{count} 项已启用',
  '{count} paused': '{count} 项已暂停',
  'Showing {count} connectors': '显示 {count} 个连接器',
  '{count} connected accounts': '已连接 {count} 个账号',
  'Compared with {branch}': '对比 {branch}',
  'Copied': '已复制',
  'Untracked': '未跟踪',
  'Failed to load commit files': '加载 Commit 文件失败',
  'Failed to load plugins': '加载插件失败',
  'Failed to load apps': '加载应用失败',
  'Failed to load Composio connectors': '加载 Composio 连接器失败',
  'Failed to load MCP servers': '加载 MCP 服务器失败',
  'Failed to load plugin': '加载插件失败',
  'Failed to load Composio connector': '加载 Composio 连接器失败',
  'Failed to start Composio login': '启动 Composio 登录失败',
  'Failed to install Composio CLI': '安装 Composio CLI 失败',
  'Failed to install plugin': '安装插件失败',
  'Failed to uninstall plugin': '卸载插件失败',
  'Failed to update plugin': '更新插件失败',
  'Failed to update app': '更新应用失败',
  'Failed to reload MCP servers': '重新加载 MCP 服务器失败',
  'Target folder': '目标文件夹',
  'Clone parent folder': '克隆到父目录',
  'Project directory: {path}': '项目目录：{path}',
  'Enter a project name.': '请输入项目名称。',
  'Enter an absolute target folder path.': '请输入目标文件夹的绝对路径。',
  'Failed to create or clone project.': '创建或克隆项目失败。',
  'Uncommitted changes': '未提交的更改',
  'Review Worktree Changes': "查看工作树更改",
  'Detached HEAD': '游离 HEAD',
  'Current branch': '当前分支',
  'Send feedback': '发送反馈',
  'Commit files': 'Commit 文件',
  'Copied commit ref': '已复制 Commit 引用',
  'Copy {sha}': '复制 {sha}',
  'Loading files...': '正在加载文件…',
  'No file changes.': '没有文件更改。',
  'Branch commits': '分支 Commit',
  'Search commits...': '搜索提交',
  'Reset-history refs': 'Reset 历史引用',
  'Select a branch.': '请选择分支。',
  'Loading commits...': '正在加载提交…',
  'current': '当前',
  'remote': '远程',
  'No commits found.': '未找到提交。',
  'Branches': '分支',
  'No branches found.': '未找到分支。',
  'Loading branch...': '正在加载分支…',
  'Git branch: {branch}': 'Git 分支：{branch}',
  'Show {sha} files': '查看 {sha} 的文件',
  'Detached {sha}': '游离 HEAD {sha}',
  'Tracked changes must be committed, stashed, or discarded before switching or resetting. Untracked files are allowed unless Git would overwrite them.': '切换分支或 Reset 前，请先 Commit、Stash 或丢弃已跟踪文件的更改。未跟踪文件可以保留，除非 Git 会覆盖它们。',
  'Plugins and Apps announcement': '插件与应用介绍',
  'Example integrations': '集成示例',
  'Confirm': '确认',
  'Confirm delete': '确认删除',
  'Target': '目标',
  'Automation target type': '自动化目标类型',
  'Schedule': '计划',
  'Automation schedule type': '自动化计划类型',
  'Run every day at': '每天运行时间',
  'Run every': '运行间隔',
  'Unit': '单位',
  'Manage automations…': '管理自动化…',
  'Add automation…': '添加自动化…',
  'Show less': '收起',
  'Show more': '展开更多',
  'Copy chat': "复制会话",
  'Open this chat before copying': "请先打开此会话再复制",
  'Unpin thread': "取消固定会话",
  'Pin thread': "固定会话",
  'Archive and remove': '归档并移除',
  'Delete': '删除',
  'Select project': '选择项目',
  'Select chat': "选择会话",
  'Search options...': '搜索选项',
  'Title': '标题',
  'Body': '正文',
  'Search titles': '搜索标题',
  'Search messages': '搜索正文',
  'Search scope': '搜索范围',
  'Search projects': '搜索项目',
  'Search chats': "搜索会话",
  'Running…': '运行中…',
  'Run now': '立即运行',
  'Not scheduled': '尚未安排',
  'Project automation requires a resolved absolute project path.': '项目自动化需要有效的项目绝对路径。',
  'Automation saved.': '自动化已保存。',
  'Automation run queued.': '自动化已加入运行队列。',
  'Failed to save automation': '保存自动化失败',
  'Failed to remove automation': '移除自动化失败',
  'Failed to run automation': '运行自动化失败',
  'Awaiting approval': '等待批准',
  'Awaiting response': '等待回复',
  'Create a new automation': '创建自动化',
  'Loading automations...': '正在加载自动化…',
  'No automations yet': '暂无自动化',
  'Use a thread or project menu to add an automation.': "通过会话或项目菜单添加自动化。",
  'Automations': '自动化',
  'API Proxy': 'API 代理',
  'Codex client access': 'Codex 客户端接入',
  'Automation details': '自动化详情',
  'Refreshing...': '正在刷新…',
  'Heartbeat': '心跳任务',
  'Project': '项目',
  'Every minute': '每分钟',
  'Hourly': '每小时',
  'Daily': '每天',
  'Weekly': '每周',
  'Custom schedule': '自定义计划',
  'Every {count} minutes': '每 {count} 分钟',
  'Every {count} hours': '每 {count} 小时',
  'Failed to load automations': '加载自动化失败',
  'Resize file list': '调整文件列表宽度',
  'Remove {name}': '移除 {name}',
  'Remove folder {name}': '移除文件夹 {name}',
  'Open {name} SKILL.md': '打开 {name} 的 SKILL.md',
  'Remove skill {name}': '移除技能 {name}',
  '{count} files': '{count} 个文件',
  '{percent}% uploading ({processed}/{total})': '正在上传 {percent}%（{processed}/{total}）',
  'Skills & Apps': '技能与应用',
  'Directory sections': '目录分类',
  'Search plugins...': '搜索插件…',
  'Search plugins': '搜索插件',
  'Sort plugins': '插件排序',
  'Loading plugins...': '正在加载插件…',
  'No plugins found.': '未找到插件。',
  'Search apps...': '搜索应用…',
  'Search apps': '搜索应用',
  'Sort apps': '应用排序',
  'Loading apps...': '正在加载应用…',
  'No apps found.': '未找到应用。',
  'Search Composio connectors...': '搜索 Composio 连接器…',
  'Search Composio connectors': '搜索 Composio 连接器',
  'Sort Composio connectors': 'Composio 连接器排序',
  'Loading Composio connectors...': '正在加载 Composio 连接器…',
  'Composio CLI is not installed in this environment.': '当前环境尚未安装 Composio CLI。',
  'Connector catalog preview': '连接器目录预览',
  'Connect everyday apps like Gmail, Calendar, Reddit, YouTube, and Drive.': '连接 Gmail、Calendar、Reddit、YouTube 和 Drive 等常用应用。',
  'Preview': '预览',
  'Composio workspace': 'Composio 工作区',
  'No Composio connectors found.': '未找到 Composio 连接器。',
  'No auth': '无需认证',
  'Loading MCP servers...': '正在加载 MCP 服务器…',
  'No MCP servers configured.': '尚未配置 MCP 服务器。',
  'Tools': '工具',
  'Resources': '资源',
  'Close plugin detail': '关闭插件详情',
  'Loading plugin...': '正在加载插件…',
  'Capabilities': '功能',
  'Apps': '应用',
  'GPT Plus account required': '需要 GPT Plus 账号',
  'MCP servers': 'MCP 服务器',
  'Apps needing auth': '需要认证的应用',
  'Close Composio detail': '关闭 Composio 详情',
  'Loading connector...': '正在加载连接器…',
  'Overview': '概览',
  'Connections': '连接',
  'Useful tools': '常用工具',
  'Manage': '管理',
  'Starting...': '启动中…',
  'Try it!': '试用',
  'Install Composio': '安装 Composio',
  'Opening...': '打开中…',
  'Login to Composio': '登录 Composio',
  'Loading...': '加载中…',
  'Load more': '加载更多',
  'Authenticate': '认证',
  'Reconnect': '重新连接',
  'Connect': '连接',
  'Expired': '已过期',
  'Failed': '失败',
  'Pending': '等待中',
  'OpenAI catalog': 'OpenAI 目录',
  'Ecosystem directory': '生态目录',
  'Logged in': '已登录',
  'Bearer token': 'Bearer Token',
  'Login required': '需要登录',
  'Auth unsupported': '不支持认证',
  'Status unknown': '状态未知',
  'No auth required': '无需认证',
  'Plugins': '插件',
  'Plugins make Codex work your way.': '通过插件扩展 Codex 的工作方式。',
  'Connect Codex to external apps and services.': '将 Codex 连接到外部应用和服务。',
  'Browse Composio connectors, auth state, and ready-to-try integrations.': '浏览 Composio 连接器、认证状态及可试用的集成。',
  'MCPs first, then installed skills and GitHub sync state.': '查看 MCP、已安装技能及 GitHub 同步状态。',
  'This creates a heartbeat automation attached to the selected chat.': "为所选会话创建心跳自动化。",
  'This creates a project automation attached to the selected project folder.': '为所选项目文件夹创建项目自动化。',
  'This creates project automations attached to the selected project folder.': '为所选项目文件夹创建项目自动化。',
  'This creates heartbeat automations attached to the selected thread.': "为所选会话创建心跳自动化。",
  'minutes': '分钟',
  'hours': '小时',
  'days': '天',
  'RRULE is required.': '必须填写 RRULE。',
  'English': 'English',
  'Simplified Chinese': '简体中文',
  'Search threads': "搜索会话",
  'Filter threads...': "筛选会话...",
  'Clear search': '清除搜索',
  'Chats': "会话",
  'Projects': '项目',
  'Pinned': '已固定',
  'Chats first': "会话优先",
  'Sort by': '排序',
  'Created': '创建时间',
  'Updated': '更新时间',
  'New chat': "新会话",
  'No chats': "没有会话",
  'Skills Hub': '技能中心',
  'Expand accounts': '展开账号',
  'Collapse accounts': '折叠账号',
  'Accounts': '账号',
  'Reloading…': '重新加载中…',
  'Reload': '重新加载',
  'Run `codex login`, then click reload.': '先运行 `codex login`，然后点击重新加载。',
  'Account': '账号',
  'Workspace': '工作区',
  'Require ⌘ + enter to send': '需要 ⌘ + Enter 才发送',
  'When busy, send as': '忙碌时发送方式',
  'Steer': '引导',
  'Queue': '排队',
  'Appearance': '外观',
  'System': '跟随系统',
  'Dark': '深色',
  'Light': '浅色',
  'Chat width': "会话宽度",
  'Click to toggle dictation': '点击切换语音输入',
  'Auto send dictation': '语音输入后自动发送',
  'Provider': '提供方',
  'Choose the API provider for the Codex backend': '选择 Codex 后端使用的 API 提供方',
  'OpenRouter API key': 'OpenRouter API Key',
  'Get API key': '获取 API Key',
  'Remove custom key, use community keys': '移除自定义 key，改用社区 key',
  'Set': '设置',
  'Save': '保存',
  'API format': 'API 格式',
  'OpenRouter API format': 'OpenRouter API 格式',
  'Responses': 'Responses',
  'Completions': 'Completions',
  'OpenCode Zen API key': 'OpenCode Zen API Key',
  'Custom endpoint URL': '自定义端点 URL',
  'API key': 'API Key',
  'Custom endpoint API format': '自定义端点 API 格式',
  'UI language': '界面语言',
  'Choose the interface language for the app.': '选择应用界面语言。',
  'Dictation language': '听写语言',
  'Auto-detect': '自动检测',
  'Search language...': '搜索语言',
  'Telegram': 'Telegram',
  'Bot token': 'Bot Token',
  'Allowed Telegram user IDs': '允许的 Telegram 用户 ID',
  'Put one Telegram user ID per line or separate them with commas. Use `*` to allow all Telegram users. Unauthorized users will see their own ID in the rejection message so they can copy it here.': '每行填写一个 Telegram 用户 ID，或用逗号分隔。使用 `*` 可允许所有 Telegram 用户。未授权用户会在拒绝消息中看到自己的 ID，方便复制到这里。',
  'Saving…': '保存中…',
  'Save Telegram config': '保存 Telegram 配置',
  'Context': '上下文',
  'Worktree name and version': "工作树名称和版本",
  'Settings': '设置',
  'Toggle terminal': '切换终端',
  'Open terminal': '打开终端',
  'Terminal command': '终端命令',
  'No commands': '没有命令',
  'Search branches...': '搜索分支',
  "Let's build": '开始构建',
  'Choose folder': '选择文件夹',
  'Quick search project': '快速搜索项目',
  'Selected folder': '已选文件夹',
  'Select folder': '选择文件夹',
  'Create Project': '创建项目',
  'Create or clone': '创建或克隆',
  'Create or clone project': '创建或克隆项目',
  'Project source': '项目来源',
  'New project': '新项目',
  'Destination folder': '目标文件夹',
  'New project name': '新项目名称',
  'GitHub repository URL': 'GitHub 仓库 URL',
  'Create project': '创建项目',
  'Creating…': '创建中…',
  'Clone repository': '克隆仓库',
  'Clone from GitHub': '从 GitHub 克隆',
  'Cloning…': '克隆中…',
  'Current folder': '当前文件夹',
  'Unavailable': '不可用',
  'Opening…': '打开中…',
  'Open': '打开',
  'Show hidden folders': '显示隐藏文件夹',
  'New folder': '新建文件夹',
  'Folder name': '文件夹名称',
  'Filter folders...': '搜索文件夹',
  'Retry': '重试',
  'Loading folders…': '加载文件夹中…',
  'No folders match this filter.': '没有匹配此筛选条件的文件夹。',
  'No subfolders found here.': '这里没有子文件夹。',
  'Base branch': '基础分支',
  'Select branch': '选择分支',
  'Loading branches…': '加载分支中…',
  'No Git branches found for this folder.': '此文件夹未找到 Git 分支。',
  'Local project': '本地项目',
  'New worktree': "新工作树",
  'Service worker registration failed.': 'Service Worker 注册失败。',
  'No matching files': '没有匹配的文件',
  'Add photos & files': '添加图片和文件',
  'Add folder': '添加文件夹',
  'Take photo': '拍照',
  'In-progress send': '执行中发送',
  'Fast mode': '快速模式',
  'Plan mode': '规划模式',
  'Agent proposes a plan before acting': '代理在执行前先提出计划',
  'Model': '模型',
  'Search models...': '搜索模型...',
  'Skills': '技能',
  'Search skills...': '搜索技能',
  'Search skills and prompts...': '搜索技能和提示词',
  'Thinking': '思考中',
  'Saving thread before stop is available': "会话保存后才能停止",
  'Stop': '停止',
  'Queue message': '加入队列',
  'Send message': '发送消息',
  'Send': '发送',
  'Drop images or files': '拖放图片或文件',
  'Selected image': '已选图片',
  'Loading messages...': '加载消息中...',
  'Plan': '计划',
  'Updating': '更新中',
  'Edit this message': '编辑此消息',
  'Edit message': '编辑消息',
  'Fork thread from this response': "从此回复创建会话分支",
  'Fork': '分叉',
  'Response copied': '回复已复制',
  'Copy response': '复制回复',
  'Jump to latest': '跳转到最新',
  'Jump to latest output': '跳转到最新输出',
  'Close image preview': '关闭图片预览',
  'Expanded message image': '放大消息图片',
  'Changed files': '已更改文件',
  'Close diff viewer': '关闭 diff 查看器',
  'No diff available': '没有可用 diff',
  'This summary was restored from the final answer text, but the thread history does not include patch diff content for this file.': "此摘要是从最终回答文本恢复的，但会话历史中不包含该文件的补丁 diff 内容。",
  'Review': '审查',
  'Commit': 'Commit',
  'Close review pane': '关闭审查面板',
  'Compare': '比较',
  'Branch': '分支',
  'Changes': '更改',
  'Loading review state': '加载审查状态中',
  'This folder is not a Git repository': '此文件夹不是 Git 仓库',
  'Initialize Git to review local changes and run Codex review.': '初始化 Git 后即可审查本地更改并运行 Codex review。',
  'Initializing…': '初始化中…',
  'Initialize Git': '初始化 Git',
  'Base branch unavailable': '基础分支不可用',
  'Could not resolve `origin/HEAD`, `main`, or `master` for this repository.': '无法为此仓库解析 `origin/HEAD`、`main` 或 `master`。',
  'No changes in this scope': '此范围内没有更改',
  'No file changes in this commit.': '此提交中没有文件更改。',
  'Your current workspace is clean.': '当前工作区很干净。',
  'No merge diff found against the base branch.': '未找到相对基础分支的合并 diff。',
  'No unified diff available.': '没有可用的统一 diff。',
  'Summary': '摘要',
  'Added': '新增',
  'Deleted': '删除',
  'Renamed': '重命名',
  'Modified': '修改',
  'Repository review': '仓库审查',
  'Staged changes': '已暂存更改',
  'Workspace changes': '工作区更改',
  'Unstage all': '全部取消暂存',
  'Stage all': '全部暂存',
  'Revert all': '全部还原',
  'Unstage file': '取消暂存文件',
  'Stage file': '暂存文件',
  'Revert file': '还原文件',
  'Unstage hunk': '取消暂存代码块',
  'Stage hunk': '暂存代码块',
  'Revert hunk': '还原代码块',
  'Failed to load review snapshot': '加载审查快照失败',
  'Failed to apply review action': '应用审查操作失败',
  'Failed to initialize Git': '初始化 Git 失败',
  'Reviewing current changes': '正在审查当前更改',
  'Failed to start review': '启动审查失败',
  'Review in progress': '审查进行中',
  'Failed to load review result': '加载审查结果失败',
  'pin': '固定',
  'Worktree thread': "工作树会话",
  'Threads': "会话",
  'Organize threads': "整理会话",
  'Organize': '整理',
  'By project': '按项目',
  'Chronological list': '按时间顺序',
  'No matching threads': "没有匹配的会话",
  'Loading threads...': "加载会话中...",
  'Edit name': '编辑名称',
  'Remove': '移除',
  'Project name': '项目名称',
  'No threads': "没有会话",
  'Thread title': "会话标题",
  'Rename thread': "重命名会话",
  'Make it short and recognizable.': '尽量简短且易识别。',
  'Add title...': '输入标题...',
  'Cancel': '取消',
  'Delete thread': "删除会话",
  'Thread automation': "会话自动化",
  'This creates a heartbeat automation attached to the selected thread.': "这会创建一个附加到所选会话的心跳自动化。",
  'Name': '名称',
  'Automation name': '自动化名称',
  'Prompt': '提示词',
  'Search prompt...': '搜索提示词...',
  'Describe what the automation should do': '描述自动化需要执行的内容',
  'Schedule (RRULE)': '计划（RRULE）',
  'Status': '状态',
  'Active': '启用',
  'Paused': '暂停',
  'Expand sidebar': '展开侧边栏',
  'Collapse sidebar': '折叠侧边栏',
  'Start new thread': "新建会话",
  'No skills found': '未找到技能',
  'No results': '没有结果',
  'Approval choices': '审批选项',
  'No, and tell Codex what to do differently': '不允许，并告诉 Codex 应如何调整',
  'Skip': '跳过',
  'Server': '服务器',
  'Open authorization link': '打开授权链接',
  'Value': '值',
  'Choice': '选项',
  'Select true or false': '选择 true 或 false',
  'True': 'True',
  'False': 'False',
  'Select an option': '选择一个选项',
  'Decline': '拒绝',
  'Continue': '继续',
  'Other answer': '其他答案',
  'Fail Tool Call': '使工具调用失败',
  'Success (Empty)': '成功（空结果）',
  'Return Empty Result': '返回空结果',
  'New terminal': '新终端',
  'Hide terminal': '隐藏终端',
  'Close': '关闭',
  'Edit queued message': '编辑排队消息',
  'Send now without interrupting work': '立即发送且不中断当前工作',
  'Delete queued message': '删除排队消息',
  'AppServer API': 'AppServer API',
  'Loading method catalog...': '加载方法目录中...',
  'Disabled': '已禁用',
  'Installed': '已安装',
  'Browse files': '浏览文件',
  'Loading skill contents...': '加载技能内容中...',
  'View on GitHub': '在 GitHub 查看',
  'Show all': '显示全部',
  'Hide all': '隐藏全部',
  'No types yet': '还没有类型',
  'Manage installed skills on this machine': '管理此机器上已安装的技能',
  'Skills Sync (GitHub)': '技能同步（GitHub）',
  'Connected': '已连接',
  'Logged in as': '已登录为',
  'Not connected': '未连接',
  'Startup': '启动',
  'Action': '动作',
  'Manual sync': '手动同步',
  'GitHub device login': 'GitHub 设备登录',
  'and enter code:': '并输入代码：',
  'Login with GitHub': '使用 GitHub 登录',
  'Device Login': '设备登录',
  'Logout GitHub': '退出 GitHub',
  'Syncing...': '同步中...',
  'Startup Sync': '启动同步',
  'Pulling...': 'Pull 中…',
  'Pull': 'Pull',
  'Pushing...': 'Push 中…',
  'Push': 'Push',
  'Installed ({count})': '已安装（{count}）',
  'Find skills': '查找技能',
  'Skills directory': '技能目录',
  'Search skills': '搜索技能',
  'Search': '搜索',
  'Search the Skills registry with npx skills find.': '使用 npx skills find 搜索 Skills 注册表。',
  'Searching...': '搜索中...',
  'Search results ({count})': '搜索结果（{count}）',
  'No matching skills found.': '未找到匹配的技能。',
  'No installed skills found.': '未找到已安装的技能。',
  'Continue in': '运行方式',
  'Search daily': '搜索（日）',
  'Search weekly': '搜索（周）',
  'Search monthly': '搜索（月）',
  'Trending daily': '热门（日）',
  'Trending weekly': '热门（周）',
  'Trending monthly': '热门（月）',
  'Newest': '最新',
  'A-Z': 'A-Z',
  'Loading skills...': '加载技能中...',
  'Choose a thread': "选择一个会话",
  'New worktree branch will start from {branch}.': "新工作树分支将从 {branch} 开始。",
  'Local project uses the selected folder directly. New worktree creates an isolated Git worktree before the first prompt.': "本地项目会直接使用所选文件夹。新工作树会在第一次提问前创建一个隔离的 Git worktree。",
  'Not configured': '未配置',
  'Online': '在线',
  'Configured (offline)': '已配置（离线）',
  'allow all users': '允许所有用户',
  'allowed user(s)': '个允许用户',
  'chat(s)': "个会话",
  'thread(s)': "个会话",
  'error': '错误',
  'unknown': '未知',
  'Switching…': '切换中…',
  'Switch': '切换',
  'Removing…': '移除中…',
  'Click again to remove': '再次点击以移除',
  '402 Payment Required': '402 需要付费',
  'primary remaining': '主额度剩余',
  'Unlimited credits': '无限点数',
  'credits': '点数',
  'Loading quota…': '加载额度中…',
  'Quota unavailable': '额度不可用',
  'Fetching account details…': '获取账号详情中…',
  'Unavailable account': '不可用账号',
  'Waiting for Codex thread/tokenUsage/updated events for this thread.': "等待此会话的 Codex tokenUsage 更新事件。",
  'Current context usage': '当前上下文使用量',
  'Cumulative thread usage': "累计会话使用量",
  'Model context window': '模型上下文窗口',
  'Remaining context': '剩余上下文',
  'tokens': 'tokens',
  'Model context window is unavailable in the latest usage event.': '最新使用事件中未提供模型上下文窗口。',
  'Awaiting data': '等待数据中',
  'left': '剩余',
  'used': '已用',
  'Updates after the next token usage event': '下次 token 使用事件后更新',
  'Window size unavailable': '窗口大小不可用',
  'Telegram bot token is required.': '需要填写 Telegram Bot Token。',
  'At least one allowed Telegram user ID or * is required.': '至少需要一个允许的 Telegram 用户 ID 或 `*`。',
  'Telegram bot configured. Only allowlisted Telegram users can use the bridge.': 'Telegram 机器人已配置。只有白名单中的 Telegram 用户可以使用桥接。',
  'Failed to connect Telegram bot': '连接 Telegram 机器人失败',
  'Failed to load accounts': '加载账号失败',
  'Failed to refresh accounts': '刷新账号失败',
  'Failed to refresh account quota': '刷新账号额度失败',
  'Login': '登录',
  'Add account': '添加账号',
  'Re-authenticate': '重新登录',
  'Re-authenticate account': '重新登录账号',
  'Refresh quota': '刷新额度',
  'Refreshing…': '刷新中…',
  'Starting login…': '正在启动登录…',
  'Open login URL': '打开登录链接',
  'Paste localhost callback URL': '粘贴 localhost 回调 URL',
  'Complete Codex login': '完成 Codex 登录',
  'Finish login in the browser, then paste the localhost callback URL here.': '在浏览器中完成登录，然后在这里粘贴 localhost 回调 URL。',
  'Complete': '完成',
  'Completing…': '正在完成…',
  'Failed to start Codex login': '启动 Codex 登录失败',
  'Failed to complete Codex login': '完成 Codex 登录失败',
  'Click Login, or run `codex login`, then click reload.': '点击登录，或运行 `codex login`，然后点击重新加载。',
  'No accounts yet. Add one from this panel.': '尚无账号，请从此面板添加。',
  'Signing in adds or refreshes an account without switching the active quota source.': '登录只会添加或刷新账号，不会切换当前额度来源。',
  'Expected account: {account}': '预期账号：{account}',
  'Account added.': '账号已添加',
  'Account sign-in refreshed.': '认证已更新',
  'Account switched.': '账号已切换',
  'Sign-in required': '需要重新登录',
  'Payment required': '需要处理付费状态',
  'Verification stale': '验证信息已过期',
  'Temporary error': '临时错误',
  'Recovery required': '需要恢复',
  'Ready': '就绪',
  'Finish the current turn and pending requests before switching accounts.': "请先完成当前回合并处理待处理请求后再切换账号。",
  'Failed to switch account': '切换账号失败',
  'Finish the current turn and pending requests before removing the active account.': "请先完成当前回合并处理待处理请求后再移除当前活动账号。",
  'Failed to remove account': '移除账号失败',
  'enabled': '已启用',
  'disabled': '已禁用',
  'Saving speed setting...': '保存速度设置中...',
  'About 1.5x faster, with credits used at 2x': '速度约提升 1.5 倍，额度消耗为 2 倍',
  'Default speed with normal credit usage': '默认速度，按正常额度消耗',
  'Stop dictation': '停止听写',
  'Click to dictate': '点击开始听写',
  'Hold to dictate': '按住听写',
  'failed': '失败',
  'attaching': '正在附加',
  'Attaching': '正在附加',
  'Attaching file...': '正在附加文件...',
  'files...': '个文件...',
  'attached': '已附加',
  'Could not attach file.': '无法附加文件。',
  'Could not attach': '无法附加',
  'files.': '个文件。',
  'Select a thread to send a message': "选择一个会话后才能发送消息",
  'Loading models for plan mode...': '正在为规划模式加载模型...',
  'Type a message... (@ for files)': '输入消息...（@ 选择文件）',
  'Hide': '隐藏',
  'Terminal': '终端',
  'Terminal input failed': '终端输入失败',
  'Terminal attach failed': '终端附加失败',
  'Creating worktree': "创建工作树",
  'Creating a worktree and running setup.': "正在创建工作树并执行初始化。",
  'Worktree setup failed': "工作树初始化失败",
  'Unable to create worktree. Try again or switch to Local project.': "无法创建工作树。请重试，或切换到本地项目。",
  'Edit': '编辑',
  'image': '图片',
  'images': '图片',
  'file': '文件',
  'files': '文件',
  'skill': '技能',
  'skills': '技能',
  '(empty queued message)': '（空的排队消息）',
  'Files': '文件',
  'Unstaged': '未暂存',
  'Staged': '已暂存',
  'Refresh': '刷新',
  'Against': '对比',
  'selected': '已选',
  'Reject Request': '拒绝请求',
  'Uninstalling...': '卸载中...',
  'Uninstall': '卸载',
  'Installing...': '安装中...',
  'Install': '安装',
  'Disable': '禁用',
  'Enable': '启用',
  'When enabled, press Enter to send. When disabled, use Command+Enter to send.': '启用时按 Enter 发送；禁用时使用 Command+Enter 发送。',
  'If a turn is still running, choose whether a new prompt should steer the current turn or be queued.': "如果当前回合仍在运行，选择新提示是引导当前回合还是加入队列。",
  'Switch between system theme, light mode, and dark mode.': '在跟随系统、浅色和深色主题之间切换。',
  'Choose how wide the conversation column and composer can grow on desktop screens.': '选择桌面端会话列和输入框的最大宽度。',
  'Use click-to-start and click-to-stop dictation instead of hold-to-talk.': '使用点击开始/停止听写，而不是按住说话。',
  'Automatically send transcribed dictation when recording stops.': '录音停止后自动发送转写结果。',
  'Show or hide GitHub trending project cards on the new thread screen.': "显示或隐藏新会话页面上的 GitHub 热门项目卡片。",
  'Choose transcription language or keep auto-detect.': '选择转写语言，或保持自动检测。',
  'Standard': '标准',
  'Wide': '宽',
  'Extra wide': '超宽',
  "Create conversation fork": "创建会话分支",
  "Existing conversation": "已有会话",
  "Conversation menu": "会话菜单",
  "Archive conversation and remove automations?": "归档会话并移除自动化？",
  "Delete conversation?": "删除会话？",
  "Archive {title}. You can find it later in archived conversations.": "归档“{title}”。之后可在已归档会话中找到它。",
  "Copy conversation": "复制会话",
  "Open this conversation before copying": "请先打开此会话再复制",
  "Unpin conversation": "取消固定会话",
  "Pin conversation": "固定会话",
  "Select conversation": "选择会话",
  "Search conversations": "搜索会话",
  "Use a conversation or project menu to add an automation.": "通过会话或项目菜单添加自动化。",
  "This creates a heartbeat automation attached to the selected conversation.": "这会创建一个附加到所选会话的心跳自动化。",
  "This creates heartbeat automations attached to the selected conversation.": "为所选会话创建心跳自动化。",
  "Filter conversations...": "筛选会话...",
  "Conversations": "会话",
  "Conversations first": "会话优先",
  "New conversation": "新会话",
  "No conversations": "没有会话",
  "Conversation width": "会话宽度",
  "Reasoning effort": "推理强度",
  "Saving conversation before stop is available": "会话保存后才能停止",
  "Fork conversation from this response": "从此回复创建会话分支",
  "This summary was restored from the final answer text, but the conversation history does not include patch diff content for this file.": "此摘要是从最终回答文本恢复的，但会话历史中不包含该文件的补丁 diff 内容。",
  "Worktree conversation": "工作树会话",
  "Organize conversations": "整理会话",
  "No matching conversations": "没有匹配的会话",
  "Loading conversations...": "加载会话中...",
  "Conversation title": "会话标题",
  "Rename conversation": "重命名会话",
  "Delete conversation": "删除会话",
  "Conversation automation": "会话自动化",
  "Start new conversation": "新建会话",
  "Choose a conversation": "选择一个会话",
  "conversation(s)": "个会话",
  "Waiting for Codex thread/tokenUsage/updated events for this conversation.": "等待此会话的 Codex tokenUsage 更新事件。",
  "Cumulative conversation usage": "累计会话使用量",
  "About 1.5x faster, with quota used at 2x": "速度约提升 1.5 倍，额度消耗为 2 倍",
  "Default speed with normal quota usage": "默认速度，按正常额度消耗",
  "Select a conversation to send a message": "选择一个会话后才能发送消息",
  "Show or hide GitHub trending project cards on the new conversation screen.": "显示或隐藏新会话页面上的 GitHub 热门项目卡片。",
  "Quota": "额度",
  "Unlimited quota": "无限额度",
  "Thread": "线程",
  "Thread ID": "线程 ID",
  "Internal thread": "内部线程",
  "Turn": "回合",
  "Worktree": "工作树",
  "Goal": "目标",
  "Banked reset": "重置机会",
}

const englishByChinese = Object.fromEntries(Object.entries(zhCN).map(([english, chinese]) => [chinese, english]))

const LANGUAGE_LABELS: Record<UiLanguage, string> = {
  en: 'English',
  'zh-CN': '简体中文',
}

function readStoredLanguage(): UiLanguage {
  if (typeof window === 'undefined') return 'en'
  const raw = window.localStorage.getItem(UI_LANGUAGE_STORAGE_KEY)?.trim()
  return raw === 'zh-CN' ? 'zh-CN' : 'en'
}

const currentLanguage = ref<UiLanguage>(readStoredLanguage())

function applyDocumentLanguage(language: UiLanguage): void {
  if (typeof document === 'undefined') return
  document.documentElement.lang = language === 'zh-CN' ? 'zh-CN' : 'en'
  document.documentElement.dataset.uiLanguage = language
}

applyDocumentLanguage(currentLanguage.value)

function formatTemplate(template: string, params?: Record<string, string | number>): string {
  if (!params) return template
  return template.replace(/\{(\w+)\}/g, (_match, key: string) => String(params[key] ?? ''))
}

export function setUiLanguage(language: UiLanguage): void {
  currentLanguage.value = language
  applyDocumentLanguage(language)
  if (typeof window !== 'undefined') {
    window.localStorage.setItem(UI_LANGUAGE_STORAGE_KEY, language)
    document.dispatchEvent(new Event('codexapp:language-change'))
  }
}

export function t(message: string, params?: Record<string, string | number>): string {
  const translated = currentLanguage.value === 'zh-CN' ? (Object.hasOwn(zhCN, message) ? zhCN[message] : chineseForSource(message)) : englishForSource(message, englishByChinese)
  return formatTemplate(translated, params)
}

export function useUiLanguage() {
  return {
    uiLanguage: currentLanguage,
    uiLanguageOptions: [
      { value: 'en', label: LANGUAGE_LABELS.en },
      { value: 'zh-CN', label: LANGUAGE_LABELS['zh-CN'] },
    ] as Array<{ value: UiLanguage; label: string }>,
    t,
    setUiLanguage,
  }
}
